# -*- coding: utf-8 -*-
# Copyright (C) 2021-Today: Part of NextFlowIT.
# @author:  Part of NextFlowIT.
{
    "name": "Pos Salesperson Commission",
    "summary": """salesperson commission odoo commission module pos commission sales commission management commission rules product-based commission percentage commission fixed commission odoo pos integration sales incentives commission tracking commission automation expense integration role-based access control odoo apps salesperson performance commission calculation pos order commission multi-user support business automation point of sale commission commission rule commission cashier commission admin commission manager commission employee commission pos commission employee commission cashier commission""",
    "post_init_hook": "post_init_hook",
    "description": """Automate and manage salesperson commissions in Odoo. Supports percentage and fixed commission, POS integration, product-based rules, expense generation, and role-based access control.""",
    "version": "19.0.0.0.1",
    "data": [
        "security/commission_rule.xml",
        "security/ir.model.access.csv",
        "security/ir_rules.xml",
        "views/pos_commission_line_view.xml",
        "views/pos_commission_rules_view.xml",
        "views/res_config_settings.xml",
        "views/pos_orderline.xml",
        "reports/nf_commission_report_view.xml",
        "wizard/nf_commission_report_view.xml",
        "data/product_product.xml",
        "data/ir_sequence_data.xml",
        "views/hr_expense_inherited_view.xml",
    ],
    "author": "NextFlowIT",
    "company": "NextFlow Technology",
    "maintainer": "NextFlow Technology",
    "website": "https://www.nextflow.in",
    "assets": {
        "point_of_sale._assets_pos": [
            "nf_pos_salesperson_commission/static/src/overrides/pos_store/data_service_options.js",
            "nf_pos_salesperson_commission/static/src/app/pos_saleperson_button/pos_salesperson_button.js",
            "nf_pos_salesperson_commission/static/src/app/pos_saleperson_button/pos_salesperson_button.xml",
            "nf_pos_salesperson_commission/static/src/app/popup/pos_saleperson_popup.js",
            "nf_pos_salesperson_commission/static/src/app/popup/pos_saleperson_popup.xml",
            "nf_pos_salesperson_commission/static/src/overrides/orderline/orderline.xml",
            "nf_pos_salesperson_commission/static/src/overrides/pos_order_line/pos_order_line.js",
            "nf_pos_salesperson_commission/static/src/overrides/pos_store/pos_store.js",
            "nf_pos_salesperson_commission/static/src/overrides/order_summary/order_summary.js",
        ],
    },
    "depends": ["hr", "point_of_sale", "pos_hr", "hr_expense"],
    "images": ["static/description/background.gif"],
    "license": "OPL-1",
    "application": False,
    "installable": True,
    "auto_install": False,
    "price": 60.99,
    "currency": "EUR",
}
